ml_politicas_energeticas:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: 18.218.188.185
      port: 8123 # use 9440 for native
      user: admin
      password: strongpassword
      secure: False
